config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only:[:show, :registrations]
  resources :feeds, only: [:show, :index]
  root                        to: 'static_pages#home'
  match '/about',             to: 'static_pages#about', via: 'get'
  match '/edit-source', to: 'user_feeds#edit',  via: 'get'
  match '/edit-source', to: "user_feeds#update",       via: 'put'
  match '/edit-source', to: "user_feeds#update",       via: 'patch'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :feeds

  def user_name
     "#{first_name} #{last_name}"
  end

  def to_s
    user_name
  end
end

app/controllers/user_feeds_controller.rb
class UserFeedsController < ApplicationController
  before_action :set_current_user


  def index
  end

  def show

  end

  def edit
    @all_feeds = Feed.all
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to feeds_path, notice: 'Sources were successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:feed_ids => [])
  end
end

app/views/user_feeds/edit.html.erb
<div class="page-header">
  <h1>News Sources</h1>
</div>

<div class="authform">
  <%= form_for(@user, :url => edit_source_path, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <div class="row">
      <div class="row">
        <h3>Edit Sources</h3>
        <ul class="list-group">
          <%= f.collection_check_boxes(:feed_ids, @all_feeds, :id, :feed_name) do |b| %>
          <div class="col-md-6">
            <li class="list-group-item">
              <%= b.label(:"data-value" => b.value) { b.check_box + '  ' + b.text } %>
            </li>
          </div>
          <% end %>
        </ul>
      </div>
      <div class="row">
        <div class="actions update">
          <%= f.submit "Update", :class => "button" %>
          <%= link_to "Back", :back %>
        </div>
      </div>
    </div>
  <% end %>
</div>